on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1.4.2
      with:
        node-version: 12

    - run: |
        yarn

    - run: |
        yarn test --coverage --coverageDirectory=./coverage
        
    - uses: codecov/codecov-action@v1.0.6        
